stickynotes/blog/urls.py
from django.urls import path
from .views import (
                PostListView,  
                PostDetailView, 
                PostCreateView,
                PostUpdateView,
                PostDeleteView,
                UserPostListView,
                ImageUploadView
                )
from . import views

urlpatterns = [
    path("", PostListView.as_view(), name="blog-home"),
    path("user/<str:username>", UserPostListView.as_view(), name="user-posts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post/new/", PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("about/", views.about, name="blog-about"),
    path("pageweb/", views.website, name="blog-pageweb"),
    path('upload_image/', ImageUploadView.as_view(), name='upload_image'),
] 

stickynotes/stickynotes/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'),
        name='password_reset'),

    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),

    path("", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stickynotes/blog/models.py
from django.db import models
from  django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce.models import HTMLField

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = HTMLField(null=True,blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail',kwargs={'pk':self.pk})

class Website(models.Model):
    web_name = models.CharField(max_length=100)
    web_url = models.URLField(max_length=300)

    def __str__(self):
        return self.web_name

stickynotes/blog/views.py
import os
import logging
from .models import Post, Website
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import  ListView, DetailView, CreateView, UpdateView,DeleteView,View 
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

logger = logging.getLogger(__name__)

@method_decorator(csrf_exempt, name='dispatch')
class ImageUploadView(View):
    def post(self, request, *args, **kwargs):
        try:
            image_file = request.FILES.get('file')
            if image_file:
                image_name = image_file.name
                media_directory = os.path.join('media', 'images')
                image_path = os.path.join(media_directory, image_name)

                # Create directory if it doesn't exist
                os.makedirs(media_directory, exist_ok=True)

                with open(image_path, 'wb+') as destination:
                    for chunk in image_file.chunks():
                        destination.write(chunk)
                
                return JsonResponse({'location': f'/media/images/{image_name}'})
            return JsonResponse({'error': 'No file uploaded'}, status=400)
        except Exception as e:
            logger.error("Image upload error: %s", str(e))
            return JsonResponse({'error': 'Image upload failed'}, status=500)

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        # Get the search query from the request
        q = self.request.GET.get('q', '')

        if q:
            # Filter posts by title, content, or author's username
            return Post.objects.filter(
                Q(title__icontains=q) |
                Q(content__icontains=q) |
                Q(author__username__icontains=q)
            ).order_by('-date_posted')
        else:
            # If no search query, return all posts ordered by date
            return Post.objects.all().order_by('-date_posted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')  # Pass 'q' to the template

        # Add the total post count to the context
        context['post_count'] = self.get_queryset().count()
        return context


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'     #<app>/<model>_<viewtype>.html
    context_object_name = 'posts'     
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def about(request):
    return render(request, 'blog/about.html', {'title': 'About'}) 


def website(request):
    return render(request, 'blog/pageweb.html')

stickynotes/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
    <p>this is about the blog application</p>
    <h3>for some testing purpose</h3>
{% endblock content %}

stickynotes/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    {% if title %}
        <title>stickynotes - {{ title }}</title>
    {% else %}
        <title>stickynotes</title>
    {% endif %}
</head>
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
          <div class="container-fluid">
            <!-- Replace the text with an image logo -->
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">
              Sticky Notes
          </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
              </div>

              <div>
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <!-- <button style="color:white;" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
                  <button style="background: none; border: none; color: white;" type="submit">
                    <i class="bi bi-search"></i>
                </button>
              </form>
              
              </div> 


              <!-- Navbar Right Side -->
              <div class="navbar-nav" style="margin-left:42px;">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                <!-- <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>  -->
            
                <!-- Create a form for logout that will be triggered by clicking on the Logout link -->
                <form id="logout-form" method="POST" action="{% url 'logout' %}" style="display: none;">
                    {% csrf_token %}
                </form>
                <a class="nav-item nav-link" href="#" onclick="document.getElementById('logout-form').submit(); return false;">
                    Logout
                </a>
                <div style=" line-height: 54px; height: 39px;;"><a href="{% url 'profile' %}"><img style="width: 35px; height: 35px; margin-left:50px;" class="rounded-circle account-img" src="{{ user.profile.image.url }}"></a>
                </div>

            {% else %}
                <a  class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a  class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
             
              </div>

            </div>
          </div>
        </nav>
        <br><br><br>
      </header> 
      
      
      



      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">

            <!-- For messages, we will use Bootstrap alerts. We will loop through the messages and display them in the template. 
             We will also add a check to see if there are any messages to display.
              If there are no messages, we will not display the alert block. Here is the updated base.html template: -->
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}


            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <!-- Include the website list -->
            {% include 'blog/website_list.html' %}   
          </div>
        </div>
      </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>  

stickynotes/blog/templates/blog/home.html
{% extends "blog/base.html" %} 
{% block content %} 


<p>Total Posts: {{ post_count }}</p>

{% for post in posts %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ post.author.profile.image.url }}"
    style="width: 50px; height: 50px"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted|date:"b d, Y" }}</small>
    </div>
    <h2>
      <a class="article-title" href="{% url 'post-detail' post.id %}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content|safe }}</p>
  </div>
</article>
{% endfor %} 
{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% else %}
            {% if num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}
{% endblock content %}

stickynotes/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %} {% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete Post</legend>
      <h2 class="text-danger">
        Are you sure you want to delete this post:
        <strong>{{ object.title }}</strong>?
      </h2>
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
      <a
        class="btn btn-outline-secondary"
        href="{% url 'post-detail' object.id %}"
        >Cancel</a
      >
    </div>
  </form>
</div>
{% endblock content %}

stickynotes/blog/templates/blog/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    {% if title %}
        <title>stickynotes - {{ title }}</title>
    {% else %}
        <title>stickynotes</title>
    {% endif %}
</head>
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
          <div class="container-fluid">
            <!-- Replace the text with an image logo -->
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">
              Sticky Notes
          </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
              </div>

              <div>
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <!-- <button style="color:white;" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
                  <button style="background: none; border: none; color: white;" type="submit">
                    <i class="bi bi-search"></i>
                </button>
              </form>
              
              </div> 


              <!-- Navbar Right Side -->
              <div class="navbar-nav" style="margin-left:42px;">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                <!-- <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>  -->
            
                <!-- Create a form for logout that will be triggered by clicking on the Logout link -->
                <form id="logout-form" method="POST" action="{% url 'logout' %}" style="display: none;">
                    {% csrf_token %}
                </form>
                <a class="nav-item nav-link" href="#" onclick="document.getElementById('logout-form').submit(); return false;">
                    Logout
                </a>
                <div style=" line-height: 54px; height: 39px;;"><a href="{% url 'profile' %}"><img style="width: 35px; height: 35px; margin-left:50px;" class="rounded-circle account-img" src="{{ user.profile.image.url }}"></a>
                </div>

            {% else %}
                <a  class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a  class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
             
              </div>

            </div>
          </div>
        </nav>
        <br><br><br>
      </header> 
      
      
      



      <main role="main" class="container">
        <div class="row">
          <div class="col-md-17">

            <!-- For messages, we will use Bootstrap alerts. We will loop through the messages and display them in the template. 
             We will also add a check to see if there are any messages to display.
              If there are no messages, we will not display the alert block. Here is the updated base.html template: -->
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}


        
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ object.author.profile.image.url }}"
    style="width: 50px; height: 50px"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
      <small class="text-muted">{{ object.date_posted|date:"b d, Y" }}</small>
      {% if object.author == user %}
      <div>
        <a
          class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{% url 'post-update' object.id %}"
          >Update</a>
        <a
          class="btn btn-danger btn-sm mt-1 mb-1"
          href="{% url 'post-delete' object.id %}"
          >Delete</a
        >
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ object.title }}</h2>
    <p class="article-content">{{ object.content|safe }}</p>
  </div>
</article>

</div>

</div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>  

stickynotes/blog/templates/blog/post_form.html
{% extends "blog/base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section" style="border: 2px solid #90caf9; border-radius: 8px;">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Blog Post</legend>
      {{ form.media }}
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
  </form>
</div>
{% endblock content %}

stickynotes/blog/templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h3>this is master branch</h3>   
   <h2>this is master</h2>
</body>
</html>

stickynotes/blog/templates/blog/user_posts.html
{% extends "blog/base.html" %} 
{% block content %}
<h1 class="mb-4">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
{% for post in posts %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ post.author.profile.image.url }}"
    style="width: 50px; height: 50px"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted|date:"b d, Y" }}</small>
    </div>
    <h2>
      <a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
    </h2>
    <p class="article-content">{{ post.content|safe }}</p>
  </div>
</article>
{% endfor %} 
{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% else %}
            {% if num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}
{% endblock content %}

stickynotes/blog/templates/blog/website_list.html
<style>
  /* Style the content section */
  .content-section-website {
  background-color: #f9f9f9; /* Light background color */
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    margin-bottom: 20px;
}

/* Style the heading */
.content-section-website h1 {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin-bottom: 15px;
    text-align: center; /* Center the heading */
}

/* Style the paragraph */
.content-section-website p {
    font-size: 16px;
    color: #666;
    margin-bottom: 20px;
    text-align: center; /* Center the paragraph */
}

/* Style the unordered list */
.content-section-website ul {
    list-style-type: none; /* Remove bullets */
    padding-left: 0;
}

/* Style each list item */
.content-section-website ul li {
    background-color: #fff; /* White background */
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 10px;
    margin-bottom: 10px;
    transition: background-color 0.3s ease, transform 0.3s ease;
}

/* Add hover effect to list items */
.content-section-website ul li:hover {
    background-color: #f1f1f1;
    transform: translateY(-3px);
}

/* Style the links */
.content-section-website ul li a {
    text-decoration: none;
    color: #007bff;
    font-weight: bold;
}

/* Add hover effect to links */
.content-section-website ul li a:hover {
    text-decoration: underline;
}

</style>
<div class="content-section-website">
  <h1>Some Useful Sites</h1>
  <!-- Display total number of websites -->
  <p>Total Websites: {{ website_count }}</p>

  <!-- Loop through websites and display their details -->
  <ul>
      {% for website in websites %}
      <li>
          <a href="{{ website.web_url }}" target="_blank">{{ website.web_name }}</a>
      </li>
      {% empty %}
      <li>No websites available yet.</li>
      {% endfor %}
  </ul>
</div>